In [2]:
# loading the packages and modules

%matplotlib inline

# general packages
import numpy as np
import pandas as pd
import sklearn

# for statistics
import scipy.stats as stats
import statsmodels.api as sm

# for visualizations
import matplotlib.pyplot as plt
from matplotlib import rcParams

import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")

/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [3]:
#loading and cleaning the data

df = pd.read_csv("beer.csv")

df = df.drop(['review/text', 'review/timeStruct','user/birthdayRaw','user/birthdayUnix'], axis=1)

df = df.rename(index=str, columns={'beer/ABV': 'ABV', 'user/gender':'gender', 'user/ageInSeconds':'ageInSeconds'})

df = df[np.abs(df.ABV-df.ABV.mean()) <= (3*df.ABV.std())]
df = df[df.ageInSeconds.notnull()]
df = df[df.gender.notnull()]

In [5]:
df.shape

(7704, 15)

In [6]:
df.describe()

,index,ABV,beer/beerId,beer/brewerId,review/appearance,review/aroma,review/overall,review/palate,review/taste,review/timeUnix,ageInSeconds
count,7704.000000,7704.000000,7704.000000,7704.000000,7704.000000,7704.000000,7704.000000,7704.000000,7704.000000,7.704000e+03,7.704000e+03
mean,24857.609294,7.454991,21805.936397,3068.560618,3.912318,3.897326,3.912059,3.866498,3.952687,1.236645e+09,1.167445e+09
std,14371.382106,2.272365,18540.411751,5187.312029,0.590726,0.671394,0.698766,0.668260,0.714050,6.573249e+07,3.088040e+08
min,4.000000,0.500000,175.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.932515e+08,7.034366e+08
25%,12377.750000,5.500000,5441.000000,395.000000,3.500000,3.500000,3.500000,3.500000,3.500000,1.198043e+09,9.775586e+08
50%,24981.500000,7.000000,18968.000000,1199.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.248133e+09,1.096639e+09
75%,36951.750000,9.400000,34146.000000,1315.000000,4.500000,4.500000,4.500000,4.500000,4.500000,1.289380e+09,1.274541e+09
max,49974.000000,14.000000,77207.000000,26990.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1.326257e+09,3.594723e+09